-- --------------------------------------------------------
-- Хост:                         127.0.0.1
-- Версия сервера:               8.0.11 - MySQL Community Server - GPL
-- Операционная система:         Win64
-- HeidiSQL Версия:              11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Дамп структуры базы данных space_bot
CREATE DATABASE IF NOT EXISTS `space_bot` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */;
USE `space_bot`;

-- Дамп структуры для таблица space_bot.listplanet
CREATE TABLE IF NOT EXISTS `listplanet` (
  `ID` int(11) NOT NULL,
  `Planet` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `Description` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `img` text,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Table with planets and their descriptions.';

-- Дамп данных таблицы space_bot.listplanet: ~37 rows (приблизительно)
/*!40000 ALTER TABLE `listplanet` DISABLE KEYS */;
INSERT INTO `listplanet` (`ID`, `Planet`, `Description`, `img`) VALUES
	(1, 'Mercury', 'It\'Mercury! \n\nMercury is the smallest and innermost planet in the Solar System. Its orbit around the Sun takes \n    87.97 days, the shortest of all the planets in the Solar System. It is named after the Greek god Hermes (Ερμής), \n    translated into Latin Mercurius Mercury, god of commerce, messenger of the gods, mediator between gods and mortals. \n    Like Venus, Mercury orbits the Sun within Earth\'s orbit as an inferior planet, and its apparent distance from the \n    Sun as viewed from Earth never exceeds 28°. This proximity to the Sun means the planet can only be seen near the western \n    horizon after sunset or eastern horizon before sunrise, usually in twilight. At this time, it may appear as a bright star-like object, \n    but is often far more difficult to observe than Venus. The planet telescopically displays the complete range of phases, similar to Venus and \n    the Moon, as it moves in its inner orbit \n    relative to Earth, which recurs over its synodic period of approximately 116 days.', 'SolarPlanets/planet1.jpg'),
	(2, 'Venus', 'It\'Venus!\n\nVenus is the second planet from the Sun. It is named after the Roman \n    goddess of love and beauty. As the second-brightest natural object in the night sky after \n    the Moon, Venus can cast shadows and can be, on rare occasion, visible to the naked eye in \n    broad daylight. Venus lies within Earth\'s orbit, and so never appears to venture far from the Sun, \n    either setting in the west just after dusk or rising in the east a bit before dawn. Venus orbits the Sun \n    every 224.7 Earth days. With a rotation period of 243 Earth days, it takes longer to rotate about its axis \n    than any other planet in the Solar System and does so in the opposite direction to all but Uranus \n    (meaning the Sun rises in the west and sets in the east).Venus does not have any moons, a distinction it shares \n    only with Mercury among planets in the Solar System.', 'SolarPlanets/planet2.jpg'),
	(3, 'Earth', 'It\'s Earth \n\nEarth is the third planet from the Sun and the only astronomical object known to harbor life. \n    According to radiometric dating estimation and other evidence, Earth formed over 4.5 billion years ago. Earth\'s gravity interacts \n    with other objects in space, especially the Sun and the Moon, which is Earth\'s only natural satellite. Earth orbits around the Sun in 365.256 \n    solar days, a period known as an Earth sidereal year. During this time, Earth rotates about its axis 366.256 times; that is, a sidereal year has \n    366.256 sidereal days. \n    Earth\'s axis of rotation is tilted with respect to its orbital plane, producing seasons on Earth. The gravitational interaction between Earth and \n    the Moon causes tides, stabilizes Earth\'s orientation on its axis, and gradually slows its rotation. Earth is the densest planet in the Solar \n    System and the largest and most massive of the four rocky planets.', 'SolarPlanets/planet3.jpg'),
	(4, 'Mars', 'It\'s Mars \n\n Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being only larger than Mercury. \n    In English, Mars carries the name of the Roman god of war and is often referred to as the "Red Planet". The latter refers to the effect of the \n    iron oxide prevalent on Mars\'s surface, which gives it a reddish appearance distinctive among the astronomical bodies visible to the naked eye.Mars \n    is a terrestrial planet with a thin atmosphere, with surface features reminiscent of the impact craters of the Moon and the valleys, deserts and \n    polar ice caps of Earth.  The days and seasons are comparable to those of Earth, because the rotational period as well as the tilt of the rotational axis relative \n    to the ecliptic plane are similar. Mars is the site of Olympus Mons, the largest volcano and highest known mountain on any planet in the Solar \n    System and of Valles Marineris, one of the largest canyons in the Solar System. The smooth Borealis basin in the northern hemisphere covers 40% of \n    the planet and may be a giant impact feature. Mars has two moons, Phobos and Deimos, which are small and irregularly shaped. These may be captured \n    asteroids, similar to 5261 Eureka, a Mars trojan.', 'SolarPlanets/planet4.jpg'),
	(5, 'Jupiter', 'It\'s Jupiter \n\nJupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas \n    giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. \n    Jupiter is one of the brightest objects visible to the naked eye in the night sky, and has been known to ancient civilizations since before \n    recorded history. It is named after the Roman god Jupiter.When viewed from Earth, Jupiter can be bright enough for its reflected light to cast \n    visible shadows,and is on average the third-brightest natural object in the night sky after the Moon and Venus. \n    Jupiter is primarily composed of hydrogen with a quarter of its mass being helium, though helium comprises only \n    about a tenth of the number of molecules. It may also have a rocky core of heavier elements,but like the other giant planets, \n    Jupiter lacks a well-defined solid surface. Because of its rapid rotation, the planet\'s shape is that of an oblate spheroid \n    (it has a slight but noticeable bulge around the equator). The outer atmosphere is visibly segregated into several bands at different latitudes, \n    resulting in turbulence and storms along their interacting boundaries. A prominent result is the Great Red Spot, a giant storm that is known to \n    have existed since at least the 17th century when it was first seen by telescope. Surrounding Jupiter is a faint planetary ring system and a \n    powerful magnetosphere. Jupiter has 79 known moons, including the four large Galilean moons discovered by Galileo Galilei in 1610. Ganymede, \n    the largest of these, has a diameter greater than that of the planet Mercury', 'SolarPlanets/planet5.jpg'),
	(6, 'Saturn', 'It\'s Saturn \n\n Saturn is the sixth planet from the Sun and the second-largest in the Solar System, \n    after Jupiter. It is a gas giant with an average radius of about nine times that of Earth.It only has one-eighth the \n    average density of Earth; however, with its larger volume, Saturn is over 95 times more massive. Saturn is named after \n    the Roman god of wealth and agriculture; its astronomical symbol (♄) represents the god\'s sickle. \n    Saturn\'s interior is most likely composed of a core of iron–nickel and rock (silicon and oxygen compounds). \n    Its core is surrounded by a deep layer of metallic hydrogen, an intermediate layer of liquid hydrogen and liquid helium, \n    and finally a gaseous outer layer. Saturn has a pale yellow hue due to ammonia crystals in its upper atmosphere. \n    An electrical current within the metallic hydrogen layer is thought to give rise to Saturn\'s planetary magnetic field, \n    which is weaker than the Earth\'s, but has a magnetic moment 580 times that of Earth due to Saturn\'s larger size. \n    Saturn\'s magnetic field strength is around one-twentieth of Jupiter\'s.[ The outer atmosphere is generally bland and lacking in contrast, \n    although long-lived features can appear. Wind speeds on Saturn can reach 1,800 km/h (1,100 mph; 500 m/s), higher than on Jupiter, \n    but not as high as those on Neptune.In January 2019, astronomers reported that a day on the planet Saturn has been \n    determined to be 10h 33m 38s + 1m 52s \n    − 1m 19s , based on studies of the planet\'s C Ring.', 'SolarPlanets/planet6.jpg'),
	(7, 'Uranus', 'It\'s Uranus! \n\nUranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus, who, \n    according to Greek mythology, was the grandfather of Zeus (Jupiter) and father of Cronus (Saturn). It has the third-largest planetary \n    radius and fourth-largest planetary mass in the Solar System. Uranus is similar in composition to Neptune, and both have bulk chemical \n    compositions which differ from that of the larger gas giants Jupiter and Saturn. For this reason, scientists often classify Uranus and \n    Neptune as "ice giants" to distinguish them from the other gas giants. Uranus\' atmosphere is similar to Jupiter\'s and Saturn\'s in its \n    primary composition of hydrogen and helium, but it contains more "ices" such as water, ammonia, and methane, along with traces of other \n    hydrocarbons. It has the coldest planetary atmosphere in the Solar System, with a minimum temperature of 49 K (−224 °C; −371 °F), and has \n    a complex, layered cloud structure with water thought to make up the lowest clouds and methane the uppermost layer of clouds.The interior \n    of Uranus is mainly composed of ices and rock. \n    Like the other giant planets, Uranus has a ring system, a magnetosphere, and numerous moons. The Uranian system has a unique configuration \n    because its axis of rotation is tilted sideways, nearly into the plane of its solar orbit. Its north and south poles, therefore, lie where most \n    other planets have their equators. In 1986, images from Voyager 2 showed Uranus as an almost featureless planet in visible light, without the \n    cloud bands or storms associated with the other giant planets. Voyager 2 remains the only spacecraft to visit the planet. Observations from Earth \n    have shown seasonal change and increased weather activity as Uranus approached its equinox in 2007. Wind speeds can reach 250 metres per \n    second (900 km/h; 560 mph).', 'SolarPlanets/planet7.jpg'),
	(8, 'Neptune', 'It\'s Neptune \n\nNeptune is the eighth and farthest-known planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, slightly more massive than its near-twin Uranus. Neptune is denser and physically smaller than Uranus because its greater mass causes more gravitational compression of its atmosphere. The planet orbits the Sun once every 164.8 years at an average distance of 30.1 AU (4.5 billion km; 2.8 billion mi). It is named after the Roman god of the sea and has the astronomical symbol ♆, a stylised version of the god Neptune\'s trident. \n    \n    Neptune is not visible to the unaided eye and is the only planet in the Solar System found by mathematical prediction rather than by empirical \n    observation. Unexpected changes in the orbit of Uranus led Alexis Bouvard to deduce that its orbit was subject to gravitational perturbation \n    by an unknown planet. After Bouvard\'s death, the position of Neptune was predicted from his observations, independently, by John Couch Adams \n    and Urbain Le Verrier. Neptune was subsequently observed with a telescope on 23 September 1846 by Johann Galle within a degree of the position \n    predicted by Le Verrier. Its largest moon, Triton, was discovered shortly thereafter, though none of the planet\'s remaining 13 known moons were \n    located telescopically until the 20th century. The planet\'s distance from Earth gives it a very small apparent size, making it challenging to \n    study with Earth-based telescopes. Neptune was visited by Voyager 2, when it flew by the planet on 25 August 1989; Voyager 2 remains the only \n    spacecraft to visit Neptune.The advent of the Hubble Space Telescope and large ground-based telescopes with adaptive optics has recently allowed \n    for additional detailed observations from afar.', 'SolarPlanets/planet8.jpg'),
	(9, 'Tau cet e*', 'It\'s Tau cet e*!', 'Exoplanets/ex1.jpg'),
	(10, 'Kapteyn b', 'It\'s Kapteyn b!', 'Exoplanets/ex2.jpg'),
	(11, 'GJ 832c', 'It\'s GJ 832c!', 'Exoplanets/ex3.jpg'),
	(12, 'GJ 682c*', 'It\'s GJ 682c*!', 'Exoplanets/ex4.jpg'),
	(13, 'GJ 667C c', 'It\'s GJ 667C c!', 'Exoplanets/ex5.jpg'),
	(14, 'GJ 667C e*', 'It\'s GJ 667C e* !', 'Exoplanets/ex6.jpg'),
	(15, 'GJ 667C f*', 'It\'s GJ 667C f* !', 'Exoplanets/ex7.jpg'),
	(16, 'GJ 180 b*', 'It\'s GJ 180 b* !', 'Exoplanets/ex8.jpg'),
	(17, 'GJ 180 c*', 'It\'s GJ 180 c* !', 'Exoplanets/ex9.jpg'),
	(18, 'GJ 422 b*', 'It\'s GJ 422 b* !', 'Exoplanets/ex10.jpg'),
	(19, 'HD 40307 g', 'It\'s HD 40307 g !', 'Exoplanets/ex11.jpg'),
	(20, 'GJ 163 c', 'It\'s GJ 163c!', 'Exoplanets/ex12.jpg'),
	(21, 'GJ 3293 c*', 'It\'s GJ 3293 c*!', 'Exoplanets/ex13.jpg'),
	(22, 'EPIC 201367065 d', 'It\'s EPIC 201367065 d!', 'Exoplanets/ex14.jpg'),
	(23, 'Kepler-438 b', 'It\'s Kepler-438 b!', 'Exoplanets/ex15.jpg'),
	(24, 'Kepler-186 f', 'It\'s Kepler-186 f!', 'Exoplanets/ex16.jpg'),
	(25, 'Kepler-22 d', 'It\'s Kepler-22 d!', 'Exoplanets/ex17.jpg'),
	(26, 'KOI-4427 b*', 'It\'s KOI-4427 b*!', 'Exoplanets/ex18.jpg'),
	(27, 'Kepler-440 b', 'It\'s Kepler-440 b!', 'Exoplanets/ex19.jpg'),
	(28, 'Kepler-61 b', 'It\'s Kepler-61 b!', 'Exoplanets/ex20.jpg'),
	(29, 'Kepler-442 b', 'It\'s Kepler-442 b!', 'Exoplanets/ex21.jpg'),
	(30, 'Kepler-174 d', 'It\'s Kepler-174 d!', 'Exoplanets/ex22.jpg'),
	(31, 'Kepler-62 f', 'It\'s Kepler-62 f!', 'Exoplanets/ex23.jpg'),
	(32, 'Kepler-62 e', 'It\'s Kepler-62 e!', 'Exoplanets/ex24.jpg'),
	(33, 'Kepler-298 d', 'It\'s Kepler-298 d!', 'Exoplanets/ex25.jpg'),
	(34, 'Kepler-296 e', 'It\'s Kepler-296 e!', 'Exoplanets/ex26.jpg'),
	(35, 'Kepler-296 f', 'It\'s Kepler-296 f!', 'Exoplanets/ex27.jpg'),
	(36, 'Kepler-283 c', 'It\'s Kepler-283 c!', 'Exoplanets/ex28.jpg'),
	(37, 'Kepler-443 b', 'It\'s Kepler-443 b!', 'Exoplanets/ex29.jpg');
/*!40000 ALTER TABLE `listplanet` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
